[framework]
name = "zio-http"

[main]
urls.plaintext = "/plaintext"
approach = "Realistic"
classification = "Micro"
database = "None"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Netty"
webserver = "None"
versus = "None"